class Autogenerated {
  int? result;
  PaginationResult? paginationResult;
  List<Data>? data;

  Autogenerated({this.result, this.paginationResult, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result = json['result'];
    paginationResult = json['paginationResult'] != null
        ? new PaginationResult.fromJson(json['paginationResult'])
        : null;
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['result'] = this.result;
    if (this.paginationResult != null) {
      data['paginationResult'] = this.paginationResult!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PaginationResult {
  int? currentPage;
  int? limit;
  int? numberOfPage;

  PaginationResult({this.currentPage, this.limit, this.numberOfPage});

  PaginationResult.fromJson(Map<String, dynamic> json) {
    currentPage = json['currentPage'];
    limit = json['limit'];
    numberOfPage = json['numberOfPage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['currentPage'] = this.currentPage;
    data['limit'] = this.limit;
    data['numberOfPage'] = this.numberOfPage;
    return data;
  }
}

class Data {
  String? sId;
  String? userName;
  int? hospitalId;
  String? email;
  int? phoneNumber;
  String? role;
  String? department;
  String? password;
  String? createdAt;
  String? updatedAt;

  Data(
      {this.sId,
      this.userName,
      this.hospitalId,
      this.email,
      this.phoneNumber,
      this.role,
      this.department,
      this.password,
      this.createdAt,
      this.updatedAt});

  Data.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    userName = json['userName'];
    hospitalId = json['hospitalId'];
    email = json['email'];
    phoneNumber = json['phoneNumber'];
    role = json['role'];
    department = json['department'];
    password = json['password'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['userName'] = this.userName;
    data['hospitalId'] = this.hospitalId;
    data['email'] = this.email;
    data['phoneNumber'] = this.phoneNumber;
    data['role'] = this.role;
    data['department'] = this.department;
    data['password'] = this.password;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    return data;
  }
}
